version: '3.8'

services:
  app:
    container_name: ${SERVICE_APP}
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=${PORT}
    networks:
      - network_bridge
    ports:
      - 4000:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
  postgres:
    container_name: ${SERVICE_DB}
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    networks:
      - network_bridge
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/app/pg-data
volumes:
  db_data:
  nodemodules:
networks:
  network_bridge:
    driver: bridge
